### ISSUE TITLE
Conversion to list fails on 'int'

### ISSUE THREAD

**Issue by yardencsGitHub** [yardencsGitHub/tf_syllable_segmentation_annotation#6]
Line 106: When the annotation has only one syllable this line creates an error because it's being created as 'int'
This will also create an error during the conversion to 'set' a few lines below

https://github.com/yardencsGitHub/tf_syllable_segmentation_annotation/blob/bdb9a5530d14d4d34e6b88355efcaaa06a099aed/cnn_bilstm/mat_utils.py#L106

**Comment by NickleDave** [comment]
HI @yardencsGitHub 
Can you put an example annotation.mat file in the Team Drive I can use to debug this?
And can give me a little more context here or by email? Do you actually have a bird with just one syllable type or are you trying to test something?

**Comment by yardencsGitHub** [comment]
Sure.
I think what happens is that is there is an annotation entry with only one syllable (maybe a call) then the unpacking stage (various conversions to sets and lists) gets the wrong variable type.
(int instead of set or list)
I’ll upload the file (llb3_annotation_Jun_2018_emily1200.mat) to the team drive.
It has empty entries as well as entry #12 that has only one syllable.

I think that using empty entries to train is also important

On Sep 29, 2018, at 10:11 PM, David Nicholson <notifications@github.com> wrote:

HI @yardencsGitHub <https://github.com/yardencsGitHub>
Can you put an example annotation.mat file in the Team Drive I can use to debug this?
And can give me a little more context here or by email? Do you actually have a bird with just one syllable type or are you trying to test something?

**Comment by NickleDave** [comment]
Should be fixed by #7

**Comment by NickleDave** [comment]
Fixed by #7
